# Generated by Django 3.2.7 on 2022-02-24 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('submitter', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('resolved', 'resolved'), ('unresolved', 'unresolved')], default='unresolved', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Deadline', models.DateField()),
                ('status', models.CharField(choices=[('Inspection due', 'Inspection due'), ('Finalised', 'Finalised'), ('Procurement Due', 'Procurement Due'), ('Mobilisation Due', 'Mobilisation Due'), ('Construction Ongoing', 'Construction Ongoing'), ('Completed', 'Completed'), ('Handed Over', 'Handed Over')], default='Inspection due', max_length=60)),
                ('issues', models.ManyToManyField(blank=True, related_name='issuess', to='Project_Flow.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader'), ('Senior Technician', 'Senior Technician'), ('Junior Technician', 'Junior Technician')], default='Junior Technician', max_length=60)),
                ('projects', models.ManyToManyField(related_name='personnels', to='Project_Flow.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='projectsss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Project_Flow.project'),
        ),
    ]
