# Generated by Django 3.2.7 on 2022-02-24 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
